name: Release

on:
  push:
    tags:
    - 'v*'
# on:
#   push:
#     branches:
#       - '*'
#   pull_request:
#   workflow_dispatch:

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
      QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri

      - run: npm install

      - run: node script/ffmpeg.js v0.0.7

      - name: Build
        uses: tauri-apps/tauri-action@v0

      # - run: npm run tauri build
      # - run: node script/upload.js ${{ steps.get_version.outputs.VERSION }}
      - run: node script/upload.js v0.0.7

  updater:
    runs-on: ubuntu-latest
    needs: [build-release]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
      QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout repository
        uses: actions/checkout@v3

      - run: npm install
      - run: node script/publish.js v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}